### ISSUE TITLE
Import Error on deep_utils

### ISSUE THREAD

**Issue by purveshpatel511** [pooya-mohammadi/unet-skin-cancer#1]
Hey, there!

I am running the train_2016.ipynb file on the google colab and I having import error on every deep_utils functions.

I am assuming that this deep_utils modul is written by you for the projects not the pypi package we are talking about. So, I checked the deep_utils repo of yours but still not find the files and function I need for this project.

How can I get that training notebook working? Any Ideas?

**Comment by studyfight** [comment]
请问你这个问题解决了吗

**Comment by pooya-mohammadi** [comment]
@studyfight 
Please install this version: deep_utils==0.8.20 and kindly let me know whether it works or not.

**Comment by studyfight** [comment]
> [@studyfight](https://github.com/studyfight) Please install this version: deep_utils==0.8.20 and kindly let me know whether it works or not.请安装此版本：deep_utils==0.8.20，并请告知我它是否有效。

Traceback (most recent call last):
  File "G:\program\unet-skin-cancer\train.py", line 11, in <module>
    from data.data_loader import get_loader
  File "G:\program\unet-skin-cancer\data\data_loader.py", line 5, in <module>
    from deep_utils import log_print, CutMixTF
ImportError: cannot import name 'CutMixTF' from 'deep_utils'
